services:
  mariadb:
    image: mariadb:latest
    container_name: snake_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test123
      MARIADB_DATABASE: snake_db
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build: .
    container_name: snake_spring_app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/snake_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test123

volumes:
  mariadb_data:
